merge_merged_unfiltered :
	jtgalaxyParadigm.py -b "-1.3;1.3" -p small_pid_66_pathway.zip genome file:data/small_pid_66_genome.tab mRNA file:data/small_pid_66_mRNA.tab

clean :
	rm -rf  merge* clusterFiles pathway dogma config* jobs* outputFiles* params* *.dogma *.imap small_pid_66_*.tab *.err .jobTree .lastjobTree
