merge_merged_unfiltered :
	wrapParadigm.py -b "-1.3;1.3" -p small_pid_66 genome file:data/small_pid_66_genome.tab mRNA file:data/small_pid_66_mRNA.tab

clean :
	rm -rf  merge* clusterFiles config* jobs* outputFiles* params* small_pid_66_* *.dogma *.imap *.err .jobTree .lastjobTree
