merge_merged_unfiltered :
	wrapParadigm.py -b "-1.3;1.3" -p small_pid_66_pathway genome rankAllFile:data/small_pid_66_genome.tab mRNA rankAllFile:data/small_pid_66_mRNA.tab

clean :
	rm -rf  merge* clusterFiles pathway dogma config* jobs* outputFiles* params* *.dogma *.imap small_pid_66_*.tab *.err .jobTree .lastjobTree
